"use client";

import { useCallback, useEffect, useState } from "react";
import {
  BookOpen,
  Check,
  Copy,
  Download,
  ExternalLink,
  RefreshCw,
} from "lucide-react";
import {
  Badge,
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Topbar,
} from "@workspace/ui";
import { BASE_PATH, env } from "@/lib/env";

/**
 * The monolith serves Swagger UI directly at /swagger-ui/index.html
 * and the OpenAPI spec at /v3/api-docs. The page points at those
 * URLs directly — no Next route handler in between. Cross-origin is fine
 * because the monolith's CORS allows any origin with credentials.
 */
export default function ApiDocsPage() {
  const swaggerUrl = `${env.NEXT_PUBLIC_API_URL}/swagger-ui/index.html`;
  const openApiUrl = `${env.NEXT_PUBLIC_API_URL}/v3/api-docs`;
  const postmanUrl = `${BASE_PATH}/api/postman-collection`;

  const [copied, setCopied] = useState(false);
  const [iframeKey, setIframeKey] = useState(0);
  const [specStatus, setSpecStatus] = useState<"checking" | "up" | "down">(
    "checking",
  );

  // Quick liveness probe so we can show a banner if the backend isn't running.
  useEffect(() => {
    let cancelled = false;
    fetch(openApiUrl, { cache: "no-store" })
      .then((r) => {
        if (cancelled) return;
        setSpecStatus(r.ok ? "up" : "down");
      })
      .catch(() => {
        if (!cancelled) setSpecStatus("down");
      });
    return () => {
      cancelled = true;
    };
  }, [iframeKey, openApiUrl]);

  const copyOpenApiUrl = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(openApiUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback: select-and-copy is overkill; just leave the user to do it.
    }
  }, [openApiUrl]);

  return (
    <>
      <Topbar
        title="API explorer"
        subtitle="Live OpenAPI spec, Swagger UI, and a Postman collection — all auto-generated from the backend"
      />

      <main className="mx-auto flex w-full max-w-7xl flex-col gap-4 p-3 sm:p-4 sm:gap-6 lg:p-6">
        {specStatus === "down" && (
          <div className="rounded-lg border border-red-500/30 bg-red-500/5 px-4 py-3 text-sm text-red-600 dark:text-red-400">
            Couldn&apos;t reach the OpenAPI spec at{" "}
            <code className="rounded bg-red-500/10 px-1.5 py-0.5 text-xs">
              {openApiUrl}
            </code>
            . Make sure the monolith is running on port 8084.
          </div>
        )}

        {/* ── Quick actions row ──────────────────────────────────────────── */}
        <section className="grid grid-cols-1 gap-4 lg:grid-cols-3">
          <ActionCard
            icon={<BookOpen className="size-4" />}
            title="OpenAPI spec"
            description="Live JSON, regenerated by the backend on every restart."
            primary={
              <Button onClick={copyOpenApiUrl} className="w-full">
                {copied ? (
                  <>
                    <Check className="size-4" />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy className="size-4" />
                    Copy spec URL
                  </>
                )}
              </Button>
            }
            secondary={
              <a href={openApiUrl} target="_blank" rel="noopener noreferrer">
                <Button variant="outline" className="w-full">
                  <ExternalLink className="size-4" />
                  View JSON
                </Button>
              </a>
            }
          />

          <ActionCard
            icon={<Download className="size-4" />}
            title="Postman collection"
            description="OpenAPI converted to Postman v2.1 — drag the file into Postman → Import."
            primary={
              <a href={postmanUrl} download>
                <Button className="w-full">
                  <Download className="size-4" />
                  Download .json
                </Button>
              </a>
            }
            secondary={
              <p className="text-xs text-muted-foreground">
                Or in Postman: <em>Import → Link →</em> paste the OpenAPI URL.
              </p>
            }
          />

          <ActionCard
            icon={<ExternalLink className="size-4" />}
            title="Open Swagger UI"
            description="Pop the explorer out into its own tab — useful for full-screen request testing."
            primary={
              <a href={swaggerUrl} target="_blank" rel="noopener noreferrer">
                <Button variant="outline" className="w-full">
                  <ExternalLink className="size-4" />
                  Open in new tab
                </Button>
              </a>
            }
            secondary={
              <p className="text-xs text-muted-foreground break-all">
                {swaggerUrl}
              </p>
            }
          />
        </section>

        {/* ── Embedded Swagger UI ────────────────────────────────────────── */}
        <Card className="overflow-hidden">
          <CardHeader className="flex flex-row items-center justify-between gap-2 space-y-0">
            <div>
              <CardTitle className="flex items-center gap-2">
                <BookOpen className="size-4 text-[color:var(--accent)]" />
                Swagger UI
                <Badge variant="success" className="ml-1">
                  Live
                </Badge>
              </CardTitle>
              <CardDescription>
                Click <em>Authorize</em> in the embedded UI and paste your
                Bearer token to try secured endpoints.
              </CardDescription>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setIframeKey((k) => k + 1)}
            >
              <RefreshCw className="size-3.5" />
              Reload
            </Button>
          </CardHeader>
          <CardContent className="p-0">
            <iframe
              key={iframeKey}
              src={swaggerUrl}
              title="Swagger UI"
              className="block h-[80vh] w-full border-0 bg-white"
              sandbox="allow-scripts allow-forms allow-same-origin allow-popups"
            />
          </CardContent>
        </Card>
      </main>
    </>
  );
}

function ActionCard({
  icon,
  title,
  description,
  primary,
  secondary,
}: {
  icon: React.ReactNode;
  title: string;
  description: string;
  primary: React.ReactNode;
  secondary: React.ReactNode;
}) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-base">
          <span className="text-[color:var(--accent)]">{icon}</span>
          {title}
        </CardTitle>
        <CardDescription>{description}</CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col gap-2">
        {primary}
        {secondary}
      </CardContent>
    </Card>
  );
}
